[versions]
jetbrains-annotations = "26.0.2-1"
jspecify = "1.0.0"
snakeyaml = "2.2"
jackson = "2.14.3"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

[plugins]
